### ISSUE TITLE
How to inject CSS into content scripts, such as tailwindcss

### ISSUE THREAD

**Issue by h7ml** [tmkx/webx-kit#100] opened 2024-10-26 09:03 UTC
My current configuration items are as follows
![image](https://github.com/user-attachments/assets/47a10778-6fa7-48c8-8140-ad292b443fae)

**Comment by tmkx** [comment] 2024-10-26 17:16
Do you mean that you want to inline the css content?

**Comment by h7ml** [comment] 2024-10-26 17:23
Yes, it seems that this will set the default style automatically. I need to remove these default CSS styles.

**Comment by tmkx** [comment] 2024-10-26 17:42
this option may be helpful: https://rsbuild.dev/guide/basic/css-usage#inline-css-files

**Comment by tmkx** [comment] 2024-10-28 07:29
did this problem get solved? if you have any questions, please let me know.

**Comment by h7ml** [comment] 2024-10-28 08:02
I'm sorry, I saw the reply again yesterday and went to try it, and it didn't fix the CSS issue introduced by default. Sorry I forgot to reply

**Comment by tmkx** [comment] 2024-10-28 08:06
Could you provide a minimal reproduction repository? I would like to understand your scenario better, as I'm not fully clear on the problem.

**Comment by h7ml** [comment] 2024-10-28 08:17
> Could you provide a minimal reproduction repository? I would like to understand your scenario better, as I'm not fully clear on the problem.

https://github.com/h7ml/juejin-book-downloader

My repo is here, troublesome

**Comment by h7ml** [comment] 2024-10-28 09:26
But I'll add the css file 
```
createShadowRootUI({
  styles: chrome.runtime.getURL('static/css/content-script.css'),
  render({ root }) {
    createRoot(root).render(<App />);
  },
});
```

The issue has not been resolved

**Comment by tmkx** [comment] 2024-10-28 09:42
because the modal is a portal element, it's created under `document.body` by default. `createShadowRootUI.styles` will be injected under the shadow root, and the styles are isolated.

so, you need to inject the style into the `document.head` directly, or set the container of the modal to the shadow DOM via props `getContainer`.

**Comment by h7ml** [comment] 2024-10-28 09:52
Thank you very much for your patience

**Comment by h7ml** [comment] 2024-10-28 09:58
```
const linkEl = document.createElement('link');
linkEl.rel = 'stylesheet';
linkEl.href = chrome.runtime.getURL('static/css/content-script.css');
document.head.appendChild(linkEl);
```

The above code can't be used directly in my juejin.tsx file, which will freeze the whole UI interface. I tried to use the CDN resource below and it also got stuck. I can't figure out the cause of the freeze at the moment.  


```
const linkEl = document.createElement('link');
linkEl.rel = 'stylesheet';
linkEl.href = 'https://cdn.tailwindcss.com/3.4.5';
document.head.appendChild(linkEl);
```

**Comment by tmkx** [comment] 2024-10-28 10:00
make sure the snippet is executed ONCE. did you place it in a callback that may be executed multiple times

**Comment by h7ml** [comment] 2024-10-28 11:45
Yes. I'm sure he only inserted it once

**Comment by tmkx** [comment] 2024-10-28 11:58
could you push your changes to a new branch?

**Comment by tmkx** [comment] 2024-10-28 12:34
1. you can add some `debugger` instructions or `alert()` calls to block the JS thread, the MutationObserver callback is falling into a loop
2. `https://cdn.tailwindcss.com/3.4.5` is a js file, please replace it with `chrome.runtime.getURL('static/css/content-script.css')`
3. make sure the css is accessible in `web_accessible_resources`

**Comment by tmkx** [comment] 2024-10-28 12:59
as I said, `https://cdn.tailwindcss.com/` is NOT a css file, you need to replace it with `chrome.runtime.getURL('static/css/content-script.css')`

**Comment by tmkx** [comment] 2024-10-28 13:07
3. make sure the css is accessible in web_accessible_resources

**Comment by h7ml** [comment] 2024-10-28 13:10
> 3. make sure the css is accessible in web_accessible_resources

Yes, this can be ensured.

**Comment by tmkx** [comment] 2024-10-28 13:10
https://github.com/tmkx/webx-kit/blob/4634f9d433883c365f728ef206b9f9ec85940bb7/examples/react/src/manifest.ts#L18-L23

**Closed** 2024-10-28 13:16 UTC

**Comment by tmkx** [comment] 2024-10-28 13:20
thank you for trying WebX-Kit. however, I will delete this issue due to potential copyright concerns.
